url: http://fabiocozzolino.azurewebsites.net
title: Fabio Cozzolino's blog
name: 'Fabio Cozzolino&#039;s blog'
description: >
  A lap around Microsoft .NET, Xamarin,
  Integration, WCF, Azure...
highlighter: rouge

permalink: ':title/'
site-twitter: fabiocozzolino

# Author Settings
author: Fabio Cozzolino # add your name
author-img: fabio.jpeg # add your photo
about-author: Hi, welcome to my blog! Here you'll find post about my passions, ideas, code and all the things that I like to share. Enjoy all the content and feel free to tell me what you think! # add description
twitter: fabiocozzolino # add your Twitter handle
facebook: fabio.cozzolino.10 # add your Facebook handle
github: fabiocozzolino # add your Github handle
linkedin: cozzolinofabio # add your Linkedin handle
email: me@fabiocozzolino.eu # add your Email address

# Disqus
discus-identifier: fabiocozzolino # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

plugins_dir:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 10
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
