url: http://fabiocozzolino.azurewebsites.net
name: 'Fabio Cozzolino&#039;s blog'
description: >
  A lap around Microsoft .NET, Xamarin,
  Integration, WCF, Azure...
highlighter: true

permalink: ':title/'
site-twitter: fabiocozzolino

# Author Settings
author: Fabio Cozzolino # add your name
#author-img: david-freeman.jpg # add your photo
#about-author: I am a web developer focusing on front-end development. Always hungry to keep learning. # add description
twitter: fabiocozzolino # add your Twitter handle
facebook: # add your Facebook handle
github: fabiocozzolino # add your Github handle
linkedin: # add your Linkedin handle
email: # add your Email address

# Disqus
discus-identifier: fabiocozzolino # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins_dir:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
